[General]
Daemon=0
Channels=7                      # Minimum channels 1, maximum 7
Delay=10                        # DMR delay in samples, can be negative
RSSICalibration=50              # Adjust according to RxGain

[Log]
# Logging levels, 0=No logging
DisplayLevel=1

[Modem]
RxFrequency=431825000
TxFrequency=434825000

# For the SXceiver
# Type=sx
# SampleRate=150000
# RxGain=50
# TxGain=30
# RxAntenna=RX
# TxAntenna=TX

# For the Pluto SDR
# Type=plutosdr
# SampleRate=250000
# RxGain=30
# TxGain=89
# RxAntenna=A_BALANCED
# TxAntenna=A
# URI=ip:pluto.local        # Soapy URI, use usb:1.1.5 for plutosdr

# For the Lime SDR
# SampleRate=250000
# Type=limesdr
# RxGain=30
# TxGain=60
# RxAntenna=LNAH
# TxAntenna=BAND1
# URI="serial=xxxx"

# For the LimeSDR-mini or LimeNET-micro v1
Type=limesdr
SampleRate=250000
RxGain=30
TxGain=64
RxAntenna=Auto
TxAntenna=Auto
# URI="serial=xxxx"
Trace=1

[MMDVM]
HostAddress=127.0.0.1
HostPort=3335
LocalAddress=127.0.0.1
LocalPort=3334
Trace=0
