[General]
Daemon=0
Channels=7                      # Minimum channels 1, maximum 7
Delay=10                        # DMR delay in samples, can be negative
RFDelay=10                      # Initial delay in msec
RSSICalibration=70              # Subtract dB from dbFS value, change according to RxGain

[Log]
# Logging levels, 0=No logging
DisplayLevel=1

[Modem]
RxFrequency=431825000
TxFrequency=434825000
DigitalGain=35
SymbolDeviation=10

# For the SXceiver
# Type=sx
# SampleRate=150000         # must be multiple of 25000
# RxGain=50
# TxGain=30
# RxAntenna=RX
# TxAntenna=TX

# For the Pluto SDR
# Type=plutosdr
# SampleRate=250000         # must be multiple of 25000
# RxGain=30
# TxGain=86
# RxAntenna=A_BALANCED
# TxAntenna=A
# URI=ip:pluto.local        # Soapy URI, use usb:1.1.5 for plutosdr

# For the Ettus USRP
# SampleRate=250000         # must be multiple of 25000
# Type=usrp
# RxGain=40
# TxGain=80
# RxAntenna=RX2
# TxAntenna=TX/RX
# URI="serial=xxxx"


# For the Lime SDR
# SampleRate=250000         # must be multiple of 25000
# Type=limesdr
# RxGain=30
# TxGain=60
# RxAntenna=LNAH
# TxAntenna=BAND1
# URI="serial=xxxx"

# For the LimeSDR-mini or LimeNET-micro v1
Type=limesdr
SampleRate=250000           # must be multiple of 25000
RxGain=20
TxGain=64
RxAntenna=Auto
TxAntenna=Auto
# URI="serial=xxxx"

Trace=1


[MMDVM]
ModemAddress=127.0.0.1
ModemPort=48100             # this is the base start port, increment in MMDVM-IQ for each instance
LocalAddress=127.0.0.1
LocalPort=48200             # this is the base start port, increment in MMDVM-IQ for each instance
Trace=0

