[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1

[SVXLink]
ModemAddress=127.0.0.1
ModemPort=48204
LocalAddress=127.0.0.1
LocalPort=48104
SVXAddress=127.0.0.1
SVXPort=4937
LocalSVXAddress=127.0.0.1
LocalSVXPort=4938
RxGain=1000                    # Rx Audio gain (to SVXLink)
TxGain=5                       # Tx Audio gain (from SVXLink)
